version: "3.8"

services:
  db:
    container_name: postgres-local-container
    image: postgres
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgressql/data
        volume:
          nocopy: true
    ports:
      - "5432:5432"
    restart: always
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    
volumes:
  dbdata: