version: "3.8"

services:
    db:
        container_name: mysql-local-contaner
        image: mysql:latest
        volumes:
          - type: volume
            source: dbdata
            target:  /var/lib/mysql
            volume:
              nocopy: true
        ports:
          - "3306:3306" 
        environment: 
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        command: --default-authentication-plugin=mysql_native_password
        restart: always
    
volumes:
    dbdata:
