version: "3.8"

services:
  db:
    container_name: mysql-local-contaner
    image: mysql:latest
    environment: 
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306" 
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["mysqld", "--mysql-native-password=ON"]
volumes:
  db:
    driver: local
